### ISSUE TITLE
Problems with start script and build

### ISSUE THREAD

**Issue by andreoliveirapguerra** [alik0211/pokedex#11]
`'react-scripts' não é reconhecido como um comando interno                                                              ou externo, um programa operável ou um arquivo em lotes.                                                               npm ERR! code ELIFECYCLE                                                                                               npm ERR! errno 1                                                                                                       npm ERR! pokedex@3.0.0 start: `react-scripts start`                                                                    npm ERR! Exit status 1                                                                                                 npm ERR!                                                                                                               npm ERR! Failed at the pokedex@3.0.0 start script.                                                                     npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                     npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

**Comment by alik0211** [comment]
@JesuisOriginal have you installed dependencies via `npm install`?

**Comment by alik0211** [comment]
Got no response for a week. Closing issue
