### ISSUE TITLE
The githubusercontent PokeAPI links are dead

### ISSUE THREAD

**Issue by jarett-lee** [alik0211/pokedex#3]
The program tries to retrieve images from https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10147.png and other paths like it, but these links are dead.

**Comment by alik0211** [comment]
I wanted to fix this issue by reducing the limit but the limit is temporarily not working. Look https://github.com/PokeAPI/pokeapi/issues/372

I'll fix this issue as soon as it works.

**Comment by alik0211** [comment]
Good news: the fix the problems pokeapi [fixed](https://github.com/PokeAPI/pokeapi/issues/372#issuecomment-456305646) the problem at the pokedex
